services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"  # Host networking for WoL packets
    user: "568:568"  # Match your current user/group IDs
    
    volumes:
      # Main config and cache (read-write for Jellyfin to function)
      - /mnt/n100pool/apps/jellyfin/config:/config
      - /mnt/n100pool/apps/jellyfin/cache:/cache
      
      # Local storage (read-only for media)
      - /mnt/n100pool/media:/media/local:ro
      
      # Remote storage (read-only for media)
      - /mnt/n100pool/remotes/xeon_media:/media/remote:ro
      
      # Optional: hardware acceleration (uncomment if needed)
      # - /dev/dri:/dev/dri:ro
      # - /dev/video0:/dev/video0:ro
    
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
      - JELLYFIN_FFmpegPath=/usr/lib/jellyfin-ffmpeg/ffmpeg
      - JELLYFIN_LogDir=/config/log
      - JELLYFIN_DataDir=/config/data
      - JELLYFIN_ConfigDir=/config/config
      - JELLYFIN_CacheDir=/cache
      - JELLYFIN_WebDir=/usr/share/jellyfin/web
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

networks:
  default:
    name: jellyfin-network
