name: Build and Deploy Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Jellyfin.Plugin.WolWaker/Jellyfin.Plugin.WolWaker.csproj
    
    - name: Build
      run: dotnet build Jellyfin.Plugin.WolWaker/Jellyfin.Plugin.WolWaker.csproj -c Release --no-restore
    
    - name: Create plugin package
      run: |
        mkdir -p plugin-packages/WoLWaker
        cp Jellyfin.Plugin.WolWaker/bin/Release/net8.0/Jellyfin.Plugin.WolWaker.dll plugin-packages/WoLWaker/
        cp Jellyfin.Plugin.WolWaker/Web/wolwaker.html plugin-packages/WoLWaker/
        
        # Create meta.json
        cat > plugin-packages/WoLWaker/meta.json << 'EOF'
        {
          "category": "General",
          "guid": "0ee23b2e-9d4d-4b5e-a0b9-7b4e54c5a5f2",
          "name": "WoL Waker",
          "description": "Automatically wakes up archival storage servers when media is requested, enabling power-efficient operation.",
          "owner": "Remi Verhoeven",
          "version": "${{ github.ref_name }}",
          "targetAbi": "10.9.0.0",
          "overview": "A Jellyfin plugin that automatically wakes up archival storage servers when media is requested",
          "changelog": "Automated build from ${{ github.sha }}"
        }
        EOF
        
        # Create ZIP package
        cd plugin-packages
        zip -r WoLWaker@v${{ github.ref_name }}.zip WoLWaker/
        
        # Calculate checksum
        echo "CHECKSUM=$(shasum -a 256 WoLWaker@v${{ github.ref_name }}.zip | cut -d' ' -f1)" >> $GITHUB_ENV
    
    - name: Update manifest
      run: |
        # Update version and checksum in manifest
        sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.ref_name }}\"/" manifest.json
        sed -i "s/\"sourceUrl\": \".*\"/\"sourceUrl\": \"https:\/\/remiverhoeven.github.io\/jellyfin-wolwaker-plugin\/WoLWaker@v${{ github.ref_name }}.zip\"/" manifest.json
        sed -i "s/\"checksum\": \".*\"/\"checksum\": \"${{ env.CHECKSUM }}\"/" manifest.json
        sed -i "s/\"timestamp\": \".*\"/\"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"/" manifest.json
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        cname: remiverhoeven.github.io
